spring:
  datasource:
    password: ${DB_PASSWORD:jcst1997}
    url: ${DB_URL:jdbc:mysql://localhost:3306/userservice}
    username: ${DB_USERNAME:juansierra}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
server:
  port: 8081