spring:
  datasource:
    password: ${SPRING_DATASOURCE_PASSWORD:jcst1997}
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/userservice}
    username: ${SPRING_DATASOURCE_USERNAME:juansierra}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
server:
  port: 8081